import type { Metadata } from "next";
import { Header } from "./_components/Header/Header";
import { Geist, Geist_Mono } from "next/font/google";
import { CartProvider } from "./shared/cart/CartProvider";
import "./globals.scss";
import { AuthProvider } from "./shared/auth/AuthProvider";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="ru" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <AuthProvider>
          <CartProvider>
            <Suspense fallback={<div style={{ height: 60 }} />}>
              <Header />
            </Suspense>
            {children}
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
